services:
    # node:
    #     build: .
    #     ports:
    #         - 4000:4000
    keycloak:
        image: quay.io/keycloak/keycloak:26.0.5
        environment:
            KC_BOOTSTRAP_ADMIN_USERNAME: admin
            KC_BOOTSTRAP_ADMIN_PASSWORD: admin
        ports:
            - 8080:8080
            - 8443:8443
        volumes:
            - kc_data:/opt/keycloak/data/
        command: ['start-dev', '--http-port', '8080', '--https-port', '8443']
volumes:
    kc_data:
